GET http://localhost:3001/spothours HTTP/1.1

###

GET http://localhost:3001/spots/6 HTTP/1.1

###

POST http://localhost:3001/spots HTTP/1.1
content-type: application/json

{
    "name": "Test Spot",
    "address": "sample address 6",
    "phone": "555-5555",
    "host": "Test Host",
    "price": "5",
    "waiver": true
}
###

POST http://localhost:3001/spothours HTTP/1.1
content-type: application/json

{
    "sun": null,
    "mon": null,
    "tues": null,
    "wed": null,
    "thurs": null,
    "fri": null,
    "sat": null,
    "spot_id": 0
}

###

PUT http://localhost:3001/spots/8 HTTP/1.1
content-type: application/json

{
    "address" : "9710 W Tropicana Ave Suite 100, Las Vegas, NV 89147",
    "name": "Distrct Art",
    "price" : 5,
    "coord_lng": 12,
    "coord_lat": 13,
    "host": "Devian"

}
###

DELETE  http://localhost:3001/spots/7 HTTP/1.1
content-type: application/json
